<template>
  <main class="relative w-full overflow-hidden bg-background px-6 py-32 md:px-12 lg:px-24">
    <article v-if="article" class="relative z-10 mx-auto max-w-6xl">
      <NuxtLink
        :to="blogIndexPath"
        class="inline-flex items-center gap-2 text-sm font-medium text-accent transition-opacity duration-300 hover:opacity-80 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent focus-visible:ring-offset-2 focus-visible:ring-offset-background"
      >
        <span aria-hidden="true">←</span>
        {{ $t('blog.back') }}
      </NuxtLink>

      <header class="mt-10 mb-12">
        <time
          v-if="formattedDate"
          :datetime="isoDate"
          class="font-mono text-xs uppercase tracking-wider text-textMuted"
        >
          {{ $t('blog.publishedOn') }} {{ formattedDate }}
        </time>
        <h1 class="mt-4 font-display text-4xl font-bold leading-tight text-foreground md:text-5xl">
          {{ article.title }}
        </h1>
        <p v-if="article.description" class="mt-6 text-lg leading-relaxed text-textMuted">
          {{ article.description }}
        </p>
      </header>

      <ContentRenderer
        :value="article"
        class="prose-invert max-w-none text-textMuted [&_a]:text-accent [&_h1]:font-display [&_h1]:text-3xl [&_h1]:font-bold [&_h1]:text-foreground [&_h2]:mt-10 [&_h2]:font-display [&_h2]:text-2xl [&_h2]:font-semibold [&_h2]:text-foreground [&_li]:my-1 [&_p]:my-5 [&_p]:leading-relaxed [&_ul]:list-disc [&_ul]:pl-6"
      />
    </article>
  </main>
</template>

<script setup lang="ts">
const route = useRoute()
const { locale } = useI18n()
const localePath = useLocalePath()

const blogIndexPath = computed(() => localePath('/blog'))

// The locale prefix is stripped from route params by @nuxtjs/i18n, so the slug
// maps directly onto the locale-agnostic Nuxt Content path (/blog/<slug>).
const contentPath = computed(() => {
  const slug = route.params.slug
  const parts = Array.isArray(slug) ? slug : [slug]
  return `/blog/${parts.filter(Boolean).join('/')}`
})

const { data: article } = await useAsyncData(`blog-article-${contentPath.value}`, () =>
  queryCollection('blog').path(contentPath.value).where('draft', '=', false).first(),
)

if (!article.value) {
  throw createError({ statusCode: 404, statusMessage: 'Article not found', fatal: true })
}

// Resolved at SSR setup time — the 404 guard above guarantees it is present.
const post = article.value

const canonicalUrl = `https://werlesson.dev${route.path}`

const dateObj = computed(() => {
  if (!post.date) {
    return null
  }
  const d = new Date(post.date)
  return Number.isNaN(d.getTime()) ? null : d
})

const isoDate = computed(() => dateObj.value?.toISOString().slice(0, 10) ?? '')

const formattedDate = computed(() => {
  if (!dateObj.value) {
    return ''
  }
  return dateObj.value.toLocaleDateString(locale.value === 'pt' ? 'pt-BR' : 'en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
})

useSeoMeta({
  title: post.title,
  description: post.description,
  ogTitle: post.title,
  ogDescription: post.description,
  ogType: 'article',
  ogUrl: canonicalUrl,
  twitterCard: 'summary_large_image',
})

useHead({
  link: [{ rel: 'canonical', href: canonicalUrl }],
})

// Per-article Open Graph image generated by nuxt-og-image (RF-41). The module
// emits an absolute og:image URL on the canonical origin.
defineOgImageComponent('BlogPost', {
  title: post.title,
  description: post.description,
})

// Per-article BlogPosting structured data (RF-42).
useSchemaOrg([
  defineArticle({
    '@type': 'BlogPosting',
    headline: post.title,
    description: post.description,
    datePublished: post.date,
    inLanguage: post.locale === 'pt' ? 'pt-BR' : 'en-US',
  }),
])
</script>
