<template>
  <div>
    <HeroSection />
    <AboutSection />
    <ImpactSection />
    <WhatIDoSection />
    <PrinciplesSection />
    <FeaturedProjectsSection />
    <ExperienceSection />
    <StackSection />
    <CurrentlyBuildingSection />
    <BlogSection />
    <ContactSection />
  </div>
</template>

<script setup lang="ts">
import { computed, toValue } from 'vue'
import AboutSection from '~/components/sections/AboutSection.vue'
import BlogSection from '~/components/sections/BlogSection.vue'
import ContactSection from '~/components/sections/ContactSection.vue'
import CurrentlyBuildingSection from '~/components/sections/CurrentlyBuildingSection.vue'
import ExperienceSection from '~/components/sections/ExperienceSection.vue'
import FeaturedProjectsSection from '~/components/sections/FeaturedProjectsSection.vue'
import HeroSection from '~/components/sections/HeroSection.vue'
import ImpactSection from '~/components/sections/ImpactSection.vue'
import PrinciplesSection from '~/components/sections/PrinciplesSection.vue'
import StackSection from '~/components/sections/StackSection.vue'
import WhatIDoSection from '~/components/sections/WhatIDoSection.vue'

const { locale } = useI18n()
const siteConfig = useSiteConfig()

// "Senior Software Engineer" positioning (RF-40, UI-07): meta title/description
// no longer read "Fullstack Developer".
const seoTitle = computed(() =>
  locale.value === 'en'
    ? 'Werlesson — Senior Software Engineer (Vue, Nuxt & Laravel)'
    : 'Werlesson — Engenheiro de Software Sênior (Vue, Nuxt & Laravel)',
)

const seoDescription = computed(() =>
  locale.value === 'en'
    ? 'Senior Software Engineer building scalable SaaS products with Vue, Nuxt and Laravel — from architecture to production. Open to remote opportunities.'
    : 'Engenheiro de Software Sênior construindo produtos SaaS escaláveis com Vue, Nuxt e Laravel — da arquitetura à produção. Aberto a oportunidades remotas.',
)

const jobTitle = computed(() =>
  locale.value === 'en' ? 'Senior Software Engineer' : 'Engenheiro de Software Sênior',
)

const personSiteUrl = computed(() => {
  const raw = String(toValue(siteConfig.url) ?? '').replace(/\/$/, '')
  return raw || 'https://werlesson.dev'
})

// Open Graph + Twitter summary-large-image card (RF-41). The og:image itself is
// generated by nuxt-og-image below (absolute URL on the canonical origin).
useSeoMeta({
  title: seoTitle,
  description: seoDescription,
  ogTitle: seoTitle,
  ogDescription: seoDescription,
  ogType: 'website',
  ogUrl: () => toValue(personSiteUrl),
  twitterCard: 'summary_large_image',
})

// Landing Open Graph image generated by nuxt-og-image (RF-41). The module emits
// an absolute og:image URL on the canonical origin (site.url). The card carries
// the Werlesson brand lockup (see app/components/OgImage/NuxtSeo.takumi.vue), so
// the headline is the positioning and the sub-line a role-free tagline — avoids
// repeating the wordmark or the "Senior Software Engineer" phrasing.
const ogTagline = computed(() =>
  locale.value === 'en'
    ? 'Scalable SaaS products with Vue, Nuxt & Laravel — from architecture to production.'
    : 'Produtos SaaS escaláveis com Vue, Nuxt & Laravel — da arquitetura à produção.',
)

defineOgImageComponent('NuxtSeo.takumi', {
  title: () => toValue(jobTitle),
  description: () => toValue(ogTagline),
})

// RSS auto-discovery link pointing to the site-level feed route (RF-45, RF-34).
useHead({
  link: [
    {
      rel: 'alternate',
      type: 'application/rss+xml',
      title: 'Werlesson — Blog',
      href: '/rss.xml',
    },
  ],
})

useSchemaOrg([
  definePerson({
    name: 'Werlesson',
    jobTitle: () => toValue(jobTitle),
    url: () => toValue(personSiteUrl),
    knowsAbout: [
      'Software Architecture',
      'SaaS Development',
      'Vue',
      'Nuxt',
      'Laravel',
      'TypeScript',
      'System Design',
      'Frontend Architecture',
      'Performance & SEO',
    ],
    nationality: 'Brazilian',
    sameAs: ['https://github.com/werlesson', 'https://www.linkedin.com/in/werlesson'],
  }),
])
</script>
